
import Head from "next/head";
import { useHasMounted } from "../../hooks/useHasMounted";
import auth from '../../styles/auth.module.css';
import {ReactNode ,FC} from 'react';

interface authArgs  {
    children: ReactNode,
    title:string
}

const AuthLayout:FC<authArgs> = ({children,title}) => {
  return (
    <>
    <Head>
    <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>

   <header className={auth.authHeader}></header>
    
    <main>
      <section className={auth.auth_info}>
      {children} 
      </section>
     
    </main>
    </>
  )
}

export default AuthLayout