
import Head from "next/head";
import { useHasMounted } from "../../hooks/useHasMounted";
import auth from '../../styles/auth.module.css';
import {FC, ReactNode } from 'react';

interface authArgs {
    children: ReactNode,
    titlePage:string
}

const AuthLayout:FC <authArgs>= ({children,titlePage}) => {
  
  const hasMounted = useHasMounted();
  
  if (!hasMounted) {
    return null;
  }
  return (
    <>
    <Head>
    <title>{titlePage}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>

   <header className={auth.authHeader}></header>
    
    <main>
      <section className={auth.auth_info}>
      {children} 
      </section>
     
    </main>
    </>
  )
}

export default AuthLayout