
import Head from "next/head";
import auth from '../../styles/auth.module.css';
<<<<<<< HEAD
import {ReactNode } from 'react';

interface AuthArgs {
    titlePage:string,
    children:ReactNode
}

const AuthLayout = (props:authArgs) => {
=======
import {ReactNode ,FC} from 'react';

interface authArgs  {
    children: ReactNode,
    title:string
}

const AuthLayout:FC<authArgs> = ({children,title}) => {
>>>>>>> e7eff809d2fcb31e9beb3cc8e858726e38b4222d
  return (
    <>
    <Head>
    <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>

   <header className={auth.authHeader}></header>
    
    <main>
      <section className={auth.auth_info}>
      {children} 
      </section>
     
    </main>
    </>
  )
}

export default AuthLayout